### ISSUE TITLE
Rich-text editing support

### ISSUE THREAD

**Issue by briwa** [christopherkade/banner-generator#1]
Hey, I came across this on dev.to. I think the idea is brilliant, I never knew I would have needed this because I always steal photos from Unsplash for the image banner. 

I have a suggestion tho. How about rich-text feature? This allows them to maybe edit the text on the banner itself instead of the input box while allowing the text to be bolded/italic/etc. Libraries like [draft.js](https://draftjs.org/docs/getting-started) or [slate.js](https://www.slatejs.org/#/rich-text) could accomplish this. And if it's not anything fancy, I think html2canvas could still render them as images (this one I might need to test).

What do you think? Is this something you have in mind too? If it is, let me know. I am interested to work on this if you don't mind (this is because I want to validate this idea too, it might not work 😂). Thanks.

**Comment by christopherkade** [comment]
That's a great idea @briwa ! That would allow a greater customisation of the banner's content.

We do need to make sure that it won't cause of problem with `html2canvas`, as each CSS property is implemented by hand ([more info](https://html2canvas.hertzen.com/features)).

If you'd like to take the lead on that one, go ahead, but make sure to read up on the [contribution guidelines](https://github.com/christopherkade/banner-generator/blob/master/CONTRIBUTING.md) first.

Thank you ! 😄
