### ISSUE TITLE
Option to change the border's color

### ISSUE THREAD

**Issue by christopherkade** [christopherkade/banner-generator#10]
If the user clicks on the border option, display a color picker to modify its color.

**Comment by diveresque** [comment]
Hi are you still looking for some help with this? I could give it a try :)

**Comment by christopherkade** [comment]
Hello @diveresque ! Absolutely, thanks for your interest.

If you need any help feel free to ask, otherwise you can always check out the [guidelines](https://github.com/christopherkade/banner-generator/blob/master/CONTRIBUTING.md).

**Comment by diveresque** [comment]
Hi @christopherkade I made the changes (just locally so far) but I wasnt able to get the gitmoji thing happening.. I followed the directions on https://github.com/carloscuesta/gitmoji-cli for commit-hook (to be honest im not sure what that means); after I did a normal git add and commit, I was expecting some other prompt for gitmoji, but nothing appeared.. could you explain how to do it? Thanks!

**Comment by christopherkade** [comment]
Awesome, can't sait to see your work :)

The commit hook basically means it will catch any commits you make and display the prompt (which will allow you to write the commit's title, description, issue number etc.), it's nothing more than that.

Following the [hook](https://twitter.com/donavon/status/1135520568990720001) section should make everything work (as it has for me up until now, just make sure to install gitmoji-cli globally).

**Comment by diveresque** [comment]
Hm ok.. Im quite sure I installed it globally, just followed the directions:
`npm i -g gitmoji-cli`

I did get an error when running 
`gitmoji -i`

![gitmoji_error](https://user-images.githubusercontent.com/16198753/58914962-27538900-8720-11e9-9ad1-50bac6c25fdc.png)
..but I assumed it was ok because it said 'successful' at the end.. maybe it wasnt actually successful??Have you seen this error message before?

**Comment by diveresque** [comment]
Ok this is fixed now, something to do with gpg :) but i just realised I didnt create a separate branch for the changes 🤕 will work on this again tomorrow :)

**Comment by diveresque** [comment]
Let me know if you have any feedback about it, including the contributing process :)
