### ISSUE TITLE
Not displaying full banner when download it

### ISSUE THREAD

**Issue by edisonaugusthy** [christopherkade/banner-generator#13]
Am submitting - > Bug

Steps to recreate

1. change the title
2. change background and  title color
3. click on randomize (attached downloaded image)
![banner (1)](https://user-images.githubusercontent.com/22213856/59415562-55506180-8de1-11e9-9ecd-5aacd2ef88f5.png)

**Comment by christopherkade** [comment]
Hello, thanks for your bug report.

Could you please let me know which browser you're currently using? (and its version)

**Comment by edisonaugusthy** [comment]
am using  Chrome Version 75.0.3770.80

**Comment by christopherkade** [comment]
![banner (13)](https://user-images.githubusercontent.com/15229355/59417311-4bba0000-8dc7-11e9-9186-dfb3e40a7f8a.png)

I can't seem to reproduce this bug with this version of Chrome. 
Could you please try a hard refresh (Command + R on Mac, Ctrl + F5 otherwise) and try again?

**Comment by edisonaugusthy** [comment]
![banner (11)](https://user-images.githubusercontent.com/22213856/59418159-2be60480-8de6-11e9-8e33-5860c11a659c.png)
Still same result ..

**Comment by edisonaugusthy** [comment]
@christopherkade  are you able to re-produce it..?

**Comment by christopherkade** [comment]
No, I'm not able to reproduce it on both Firefox & Chrome.
